name: CI_pyFrame3DD

# We run CI on push commits and pull requests on all branches
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build_conda:
        name: Conda Build (${{ matrix.os }})
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: False
            matrix:
                os: ["ubuntu-latest", "windows-latest"]
                python-version: ["3.8", "3.9", "3.10"]

        steps:
            - uses: actions/checkout@v2
            - uses: conda-incubator/setup-miniconda@v2
              # https://github.com/marketplace/actions/setup-miniconda
              with:
                  miniconda-version: "latest"
                  channels: conda-forge
                  auto-update-conda: true
                  python-version: ${{ matrix.python-version }}
                  environment-file: environment.yml
                  activate-environment: test

            # Install dependencies of WISDEM specific to linux/mac
            #- name: Add compilers
            #  run: |
            #      conda install compilers

            # Install dependencies of WISDEM specific to linux/mac
            - name: Add dependencies linux specific
              if: false == contains( matrix.os, 'windows')
              run: |
                  conda install ninja
                  conda init bash

            # Install dependencies of WISDEM specific to windows
            - name: Add dependencies windows specific
              if: contains( matrix.os, 'windows')
              run: |
                  conda install -y m2w64-toolchain libpython

            # Install 
            - name: Conda Install pyFrame3DD
              shell: bash -l {0}
              #shell: pwsh
              run: |
                  pip install -vv --no-deps .

            # Run tests
            - name: Conda Run pytest
              shell: bash -l {0}
              #shell: pwsh
              run: |
                  pytest test

