name: CI_pyFrame3DD

# We run CI on push commits and pull requests on all branches
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build_conda:
        name: Conda Build (${{ matrix.os }})
        runs-on: ${{ matrix.os }}
        
        defaults:
            run:
                shell: bash -l {0}
                
        strategy:
            fail-fast: False
            matrix:
                os: ["ubuntu-latest", "windows-latest"]
                python-version: ["3.8", "3.9", "3.10"]

        steps:
            - name: checkout repository
              uses: actions/checkout@v2
              
            - name: Create environment
              uses: conda-incubator/setup-miniconda@v2
              # https://github.com/marketplace/actions/setup-miniconda
              with:
                  miniconda-version: "latest"
                  channels: conda-forge
                  auto-update-conda: true
                  python-version: ${{ matrix.python-version }}
                  environment-file: environment.yml
                  activate-environment: test
                  auto-activate-base: false

            # Install dependencies of WISDEM specific to linux/mac
            #- name: Add compilers
            #  run: |
            #      conda install compilers

            # Install dependencies of WISDEM specific to linux/mac
            #- name: Add dependencies linux specific
            #  if: false == contains( matrix.os, 'windows')
            #  run: |
            #      conda install ninja
            #      conda init bash

            # Install dependencies of WISDEM specific to windows
            - name: Add dependencies windows specific
              if: contains( matrix.os, 'windows')
              run: |
                  conda install -y m2w64-toolchain libpython

            # Install 
            - name: Conda Install pyFrame3DD
              run: |
                  conda activate test
                  python setup.py develop

            # Run tests
            - name: Conda Run pytest
              run: |
                  conda activate test
                  pytest test

